// Code generated by protoc-gen-go. DO NOT EDIT.
// source: 17track.proto

package track17

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 推送结果
type PushState int32

const (
	PushState_PS_NOT_PUSH PushState = 0
	PushState_PS_SUCCESS  PushState = 1
	PushState_PS_FAILURE  PushState = 2
)

var PushState_name = map[int32]string{
	0: "PS_NOT_PUSH",
	1: "PS_SUCCESS",
	2: "PS_FAILURE",
}

var PushState_value = map[string]int32{
	"PS_NOT_PUSH": 0,
	"PS_SUCCESS":  1,
	"PS_FAILURE":  2,
}

func (x PushState) String() string {
	return proto.EnumName(PushState_name, int32(x))
}

func (PushState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7603acb2f1f18262, []int{0}
}

// 运输商状态
type CarrierState int32

const (
	CarrierState_CS_UNRECOGNIZED          CarrierState = 0
	CarrierState_CS_NORMAL                CarrierState = 1
	CarrierState_CS_NOTFOUND              CarrierState = 2
	CarrierState_CS_SITE_ERR              CarrierState = 10
	CarrierState_CS_PROCESS_ERR           CarrierState = 11
	CarrierState_CS_FETCH_ERR             CarrierState = 12
	CarrierState_CS_SITE_ERR_USE_CACHE    CarrierState = 20
	CarrierState_CS_PROCESS_ERR_USE_CACHE CarrierState = 21
	CarrierState_CS_FETCH_ERR_USE_CACHE   CarrierState = 22
)

var CarrierState_name = map[int32]string{
	0:  "CS_UNRECOGNIZED",
	1:  "CS_NORMAL",
	2:  "CS_NOTFOUND",
	10: "CS_SITE_ERR",
	11: "CS_PROCESS_ERR",
	12: "CS_FETCH_ERR",
	20: "CS_SITE_ERR_USE_CACHE",
	21: "CS_PROCESS_ERR_USE_CACHE",
	22: "CS_FETCH_ERR_USE_CACHE",
}

var CarrierState_value = map[string]int32{
	"CS_UNRECOGNIZED":          0,
	"CS_NORMAL":                1,
	"CS_NOTFOUND":              2,
	"CS_SITE_ERR":              10,
	"CS_PROCESS_ERR":           11,
	"CS_FETCH_ERR":             12,
	"CS_SITE_ERR_USE_CACHE":    20,
	"CS_PROCESS_ERR_USE_CACHE": 21,
	"CS_FETCH_ERR_USE_CACHE":   22,
}

func (x CarrierState) String() string {
	return proto.EnumName(CarrierState_name, int32(x))
}

func (CarrierState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7603acb2f1f18262, []int{1}
}

// 包裹状态
type PackageState int32

const (
	PackageState_PKGS_NOTFOUND  PackageState = 0
	PackageState_PKGS_INTRANSIT PackageState = 10
	PackageState_PKGS_TOOLONG   PackageState = 20
	PackageState_PKGS_ARRIVED   PackageState = 30
	PackageState_PKGS_FAIL      PackageState = 35
	PackageState_PKGS_SUCCESS   PackageState = 40
	PackageState_PKGS_ABNORMAL  PackageState = 50
)

var PackageState_name = map[int32]string{
	0:  "PKGS_NOTFOUND",
	10: "PKGS_INTRANSIT",
	20: "PKGS_TOOLONG",
	30: "PKGS_ARRIVED",
	35: "PKGS_FAIL",
	40: "PKGS_SUCCESS",
	50: "PKGS_ABNORMAL",
}

var PackageState_value = map[string]int32{
	"PKGS_NOTFOUND":  0,
	"PKGS_INTRANSIT": 10,
	"PKGS_TOOLONG":   20,
	"PKGS_ARRIVED":   30,
	"PKGS_FAIL":      35,
	"PKGS_SUCCESS":   40,
	"PKGS_ABNORMAL":  50,
}

func (x PackageState) String() string {
	return proto.EnumName(PackageState_name, int32(x))
}

func (PackageState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7603acb2f1f18262, []int{2}
}

// 追踪状态
type TrackState int32

const (
	TrackState_TS_STOP    TrackState = 0
	TrackState_TS_RUNNING TrackState = 1
)

var TrackState_name = map[int32]string{
	0: "TS_STOP",
	1: "TS_RUNNING",
}

var TrackState_value = map[string]int32{
	"TS_STOP":    0,
	"TS_RUNNING": 1,
}

func (x TrackState) String() string {
	return proto.EnumName(TrackState_name, int32(x))
}

func (TrackState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7603acb2f1f18262, []int{3}
}

// 停止追踪原因
type StopTrackReason int32

const (
	StopTrackReason_STR_UNKNOWN         StopTrackReason = 0
	StopTrackReason_STR_EXPIRE          StopTrackReason = 1
	StopTrackReason_STR_API             StopTrackReason = 2
	StopTrackReason_STR_ARTIFICIAL      StopTrackReason = 3
	StopTrackReason_STR_INVALID_CARRIER StopTrackReason = 4
)

var StopTrackReason_name = map[int32]string{
	0: "STR_UNKNOWN",
	1: "STR_EXPIRE",
	2: "STR_API",
	3: "STR_ARTIFICIAL",
	4: "STR_INVALID_CARRIER",
}

var StopTrackReason_value = map[string]int32{
	"STR_UNKNOWN":         0,
	"STR_EXPIRE":          1,
	"STR_API":             2,
	"STR_ARTIFICIAL":      3,
	"STR_INVALID_CARRIER": 4,
}

func (x StopTrackReason) String() string {
	return proto.EnumName(StopTrackReason_name, int32(x))
}

func (StopTrackReason) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7603acb2f1f18262, []int{4}
}

// 错误返回
type Error struct {
	Code                 int32            `protobuf:"varint,1,opt,name=code,proto3" json:"code" form:"code"`
	Message              string           `protobuf:"bytes,2,opt,name=message,proto3" json:"message" form:"message"`
	Data                 *Error_ErrorData `protobuf:"bytes,3,opt,name=data,proto3" json:"data" form:"data"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_7603acb2f1f18262, []int{0}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Error) GetData() *Error_ErrorData {
	if m != nil {
		return m.Data
	}
	return nil
}

type Error_ErrorData struct {
	Errors               []*RejectError `protobuf:"bytes,1,rep,name=errors,proto3" json:"errors" form:"errors"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Error_ErrorData) Reset()         { *m = Error_ErrorData{} }
func (m *Error_ErrorData) String() string { return proto.CompactTextString(m) }
func (*Error_ErrorData) ProtoMessage()    {}
func (*Error_ErrorData) Descriptor() ([]byte, []int) {
	return fileDescriptor_7603acb2f1f18262, []int{0, 0}
}

func (m *Error_ErrorData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error_ErrorData.Unmarshal(m, b)
}
func (m *Error_ErrorData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error_ErrorData.Marshal(b, m, deterministic)
}
func (m *Error_ErrorData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error_ErrorData.Merge(m, src)
}
func (m *Error_ErrorData) XXX_Size() int {
	return xxx_messageInfo_Error_ErrorData.Size(m)
}
func (m *Error_ErrorData) XXX_DiscardUnknown() {
	xxx_messageInfo_Error_ErrorData.DiscardUnknown(m)
}

var xxx_messageInfo_Error_ErrorData proto.InternalMessageInfo

func (m *Error_ErrorData) GetErrors() []*RejectError {
	if m != nil {
		return m.Errors
	}
	return nil
}

// 错误信息
type RejectError struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code" form:"code"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message" form:"message"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RejectError) Reset()         { *m = RejectError{} }
func (m *RejectError) String() string { return proto.CompactTextString(m) }
func (*RejectError) ProtoMessage()    {}
func (*RejectError) Descriptor() ([]byte, []int) {
	return fileDescriptor_7603acb2f1f18262, []int{1}
}

func (m *RejectError) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RejectError.Unmarshal(m, b)
}
func (m *RejectError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RejectError.Marshal(b, m, deterministic)
}
func (m *RejectError) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RejectError.Merge(m, src)
}
func (m *RejectError) XXX_Size() int {
	return xxx_messageInfo_RejectError.Size(m)
}
func (m *RejectError) XXX_DiscardUnknown() {
	xxx_messageInfo_RejectError.DiscardUnknown(m)
}

var xxx_messageInfo_RejectError proto.InternalMessageInfo

func (m *RejectError) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *RejectError) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// 成功返回
type TrackAccept struct {
	Origin               int32    `protobuf:"varint,1,opt,name=origin,proto3" json:"origin" form:"origin"`
	Number               string   `protobuf:"bytes,2,opt,name=number,proto3" json:"number" form:"number"`
	Carrier              int32    `protobuf:"varint,3,opt,name=carrier,proto3" json:"carrier" form:"carrier"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TrackAccept) Reset()         { *m = TrackAccept{} }
func (m *TrackAccept) String() string { return proto.CompactTextString(m) }
func (*TrackAccept) ProtoMessage()    {}
func (*TrackAccept) Descriptor() ([]byte, []int) {
	return fileDescriptor_7603acb2f1f18262, []int{2}
}

func (m *TrackAccept) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrackAccept.Unmarshal(m, b)
}
func (m *TrackAccept) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrackAccept.Marshal(b, m, deterministic)
}
func (m *TrackAccept) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrackAccept.Merge(m, src)
}
func (m *TrackAccept) XXX_Size() int {
	return xxx_messageInfo_TrackAccept.Size(m)
}
func (m *TrackAccept) XXX_DiscardUnknown() {
	xxx_messageInfo_TrackAccept.DiscardUnknown(m)
}

var xxx_messageInfo_TrackAccept proto.InternalMessageInfo

func (m *TrackAccept) GetOrigin() int32 {
	if m != nil {
		return m.Origin
	}
	return 0
}

func (m *TrackAccept) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *TrackAccept) GetCarrier() int32 {
	if m != nil {
		return m.Carrier
	}
	return 0
}

type TrackReject struct {
	Number               string       `protobuf:"bytes,1,opt,name=number,proto3" json:"number" form:"number"`
	Error                *RejectError `protobuf:"bytes,2,opt,name=error,proto3" json:"error" form:"error"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *TrackReject) Reset()         { *m = TrackReject{} }
func (m *TrackReject) String() string { return proto.CompactTextString(m) }
func (*TrackReject) ProtoMessage()    {}
func (*TrackReject) Descriptor() ([]byte, []int) {
	return fileDescriptor_7603acb2f1f18262, []int{3}
}

func (m *TrackReject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrackReject.Unmarshal(m, b)
}
func (m *TrackReject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrackReject.Marshal(b, m, deterministic)
}
func (m *TrackReject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrackReject.Merge(m, src)
}
func (m *TrackReject) XXX_Size() int {
	return xxx_messageInfo_TrackReject.Size(m)
}
func (m *TrackReject) XXX_DiscardUnknown() {
	xxx_messageInfo_TrackReject.DiscardUnknown(m)
}

var xxx_messageInfo_TrackReject proto.InternalMessageInfo

func (m *TrackReject) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *TrackReject) GetError() *RejectError {
	if m != nil {
		return m.Error
	}
	return nil
}

type TrackReq struct {
	Number               string   `protobuf:"bytes,1,opt,name=number,proto3" json:"number" form:"number"`
	Carrier              int32    `protobuf:"varint,2,opt,name=carrier,proto3" json:"carrier" form:"carrier"`
	FinalCarrier         int32    `protobuf:"varint,3,opt,name=final_carrier,json=finalCarrier,proto3" json:"final_carrier" form:"final_carrier"`
	AutoDetection        bool     `protobuf:"varint,4,opt,name=auto_detection,json=autoDetection,proto3" json:"auto_detection" form:"auto_detection"`
	Tag                  string   `protobuf:"bytes,5,opt,name=tag,proto3" json:"tag" form:"tag"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TrackReq) Reset()         { *m = TrackReq{} }
func (m *TrackReq) String() string { return proto.CompactTextString(m) }
func (*TrackReq) ProtoMessage()    {}
func (*TrackReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_7603acb2f1f18262, []int{4}
}

func (m *TrackReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrackReq.Unmarshal(m, b)
}
func (m *TrackReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrackReq.Marshal(b, m, deterministic)
}
func (m *TrackReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrackReq.Merge(m, src)
}
func (m *TrackReq) XXX_Size() int {
	return xxx_messageInfo_TrackReq.Size(m)
}
func (m *TrackReq) XXX_DiscardUnknown() {
	xxx_messageInfo_TrackReq.DiscardUnknown(m)
}

var xxx_messageInfo_TrackReq proto.InternalMessageInfo

func (m *TrackReq) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *TrackReq) GetCarrier() int32 {
	if m != nil {
		return m.Carrier
	}
	return 0
}

func (m *TrackReq) GetFinalCarrier() int32 {
	if m != nil {
		return m.FinalCarrier
	}
	return 0
}

func (m *TrackReq) GetAutoDetection() bool {
	if m != nil {
		return m.AutoDetection
	}
	return false
}

func (m *TrackReq) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

type TrackResp struct {
	Code                 int32           `protobuf:"varint,1,opt,name=code,proto3" json:"code" form:"code"`
	Data                 *TrackResp_Data `protobuf:"bytes,2,opt,name=data,proto3" json:"data" form:"data"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *TrackResp) Reset()         { *m = TrackResp{} }
func (m *TrackResp) String() string { return proto.CompactTextString(m) }
func (*TrackResp) ProtoMessage()    {}
func (*TrackResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_7603acb2f1f18262, []int{5}
}

func (m *TrackResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrackResp.Unmarshal(m, b)
}
func (m *TrackResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrackResp.Marshal(b, m, deterministic)
}
func (m *TrackResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrackResp.Merge(m, src)
}
func (m *TrackResp) XXX_Size() int {
	return xxx_messageInfo_TrackResp.Size(m)
}
func (m *TrackResp) XXX_DiscardUnknown() {
	xxx_messageInfo_TrackResp.DiscardUnknown(m)
}

var xxx_messageInfo_TrackResp proto.InternalMessageInfo

func (m *TrackResp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *TrackResp) GetData() *TrackResp_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type TrackResp_Data struct {
	Accepted             []*TrackAccept `protobuf:"bytes,1,rep,name=accepted,proto3" json:"accepted" form:"accepted"`
	Rejected             []*TrackReject `protobuf:"bytes,2,rep,name=rejected,proto3" json:"rejected" form:"rejected"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *TrackResp_Data) Reset()         { *m = TrackResp_Data{} }
func (m *TrackResp_Data) String() string { return proto.CompactTextString(m) }
func (*TrackResp_Data) ProtoMessage()    {}
func (*TrackResp_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_7603acb2f1f18262, []int{5, 0}
}

func (m *TrackResp_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrackResp_Data.Unmarshal(m, b)
}
func (m *TrackResp_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrackResp_Data.Marshal(b, m, deterministic)
}
func (m *TrackResp_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrackResp_Data.Merge(m, src)
}
func (m *TrackResp_Data) XXX_Size() int {
	return xxx_messageInfo_TrackResp_Data.Size(m)
}
func (m *TrackResp_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_TrackResp_Data.DiscardUnknown(m)
}

var xxx_messageInfo_TrackResp_Data proto.InternalMessageInfo

func (m *TrackResp_Data) GetAccepted() []*TrackAccept {
	if m != nil {
		return m.Accepted
	}
	return nil
}

func (m *TrackResp_Data) GetRejected() []*TrackReject {
	if m != nil {
		return m.Rejected
	}
	return nil
}

type ChangeCarrierReq struct {
	Number               string   `protobuf:"bytes,1,opt,name=number,proto3" json:"number" form:"number"`
	CarrierOld           int32    `protobuf:"varint,2,opt,name=carrier_old,json=carrierOld,proto3" json:"carrier_old" form:"carrier_old"`
	CarrierNew           int32    `protobuf:"varint,3,opt,name=carrier_new,json=carrierNew,proto3" json:"carrier_new" form:"carrier_new"`
	FinalCarrierOld      int32    `protobuf:"varint,4,opt,name=final_carrier_old,json=finalCarrierOld,proto3" json:"final_carrier_old" form:"final_carrier_old"`
	FinalCarrierNew      int32    `protobuf:"varint,5,opt,name=final_carrier_new,json=finalCarrierNew,proto3" json:"final_carrier_new" form:"final_carrier_new"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeCarrierReq) Reset()         { *m = ChangeCarrierReq{} }
func (m *ChangeCarrierReq) String() string { return proto.CompactTextString(m) }
func (*ChangeCarrierReq) ProtoMessage()    {}
func (*ChangeCarrierReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_7603acb2f1f18262, []int{6}
}

func (m *ChangeCarrierReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeCarrierReq.Unmarshal(m, b)
}
func (m *ChangeCarrierReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeCarrierReq.Marshal(b, m, deterministic)
}
func (m *ChangeCarrierReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeCarrierReq.Merge(m, src)
}
func (m *ChangeCarrierReq) XXX_Size() int {
	return xxx_messageInfo_ChangeCarrierReq.Size(m)
}
func (m *ChangeCarrierReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeCarrierReq.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeCarrierReq proto.InternalMessageInfo

func (m *ChangeCarrierReq) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *ChangeCarrierReq) GetCarrierOld() int32 {
	if m != nil {
		return m.CarrierOld
	}
	return 0
}

func (m *ChangeCarrierReq) GetCarrierNew() int32 {
	if m != nil {
		return m.CarrierNew
	}
	return 0
}

func (m *ChangeCarrierReq) GetFinalCarrierOld() int32 {
	if m != nil {
		return m.FinalCarrierOld
	}
	return 0
}

func (m *ChangeCarrierReq) GetFinalCarrierNew() int32 {
	if m != nil {
		return m.FinalCarrierNew
	}
	return 0
}

type TrackUpdateReq struct {
	Number               string               `protobuf:"bytes,1,opt,name=number,proto3" json:"number" form:"number"`
	Carrier              int32                `protobuf:"varint,2,opt,name=carrier,proto3" json:"carrier" form:"carrier"`
	Items                *TrackUpdateReq_Item `protobuf:"bytes,3,opt,name=items,proto3" json:"items" form:"items"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *TrackUpdateReq) Reset()         { *m = TrackUpdateReq{} }
func (m *TrackUpdateReq) String() string { return proto.CompactTextString(m) }
func (*TrackUpdateReq) ProtoMessage()    {}
func (*TrackUpdateReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_7603acb2f1f18262, []int{7}
}

func (m *TrackUpdateReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrackUpdateReq.Unmarshal(m, b)
}
func (m *TrackUpdateReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrackUpdateReq.Marshal(b, m, deterministic)
}
func (m *TrackUpdateReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrackUpdateReq.Merge(m, src)
}
func (m *TrackUpdateReq) XXX_Size() int {
	return xxx_messageInfo_TrackUpdateReq.Size(m)
}
func (m *TrackUpdateReq) XXX_DiscardUnknown() {
	xxx_messageInfo_TrackUpdateReq.DiscardUnknown(m)
}

var xxx_messageInfo_TrackUpdateReq proto.InternalMessageInfo

func (m *TrackUpdateReq) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *TrackUpdateReq) GetCarrier() int32 {
	if m != nil {
		return m.Carrier
	}
	return 0
}

func (m *TrackUpdateReq) GetItems() *TrackUpdateReq_Item {
	if m != nil {
		return m.Items
	}
	return nil
}

type TrackUpdateReq_Item struct {
	Tag                  string   `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag" form:"tag"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TrackUpdateReq_Item) Reset()         { *m = TrackUpdateReq_Item{} }
func (m *TrackUpdateReq_Item) String() string { return proto.CompactTextString(m) }
func (*TrackUpdateReq_Item) ProtoMessage()    {}
func (*TrackUpdateReq_Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_7603acb2f1f18262, []int{7, 0}
}

func (m *TrackUpdateReq_Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrackUpdateReq_Item.Unmarshal(m, b)
}
func (m *TrackUpdateReq_Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrackUpdateReq_Item.Marshal(b, m, deterministic)
}
func (m *TrackUpdateReq_Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrackUpdateReq_Item.Merge(m, src)
}
func (m *TrackUpdateReq_Item) XXX_Size() int {
	return xxx_messageInfo_TrackUpdateReq_Item.Size(m)
}
func (m *TrackUpdateReq_Item) XXX_DiscardUnknown() {
	xxx_messageInfo_TrackUpdateReq_Item.DiscardUnknown(m)
}

var xxx_messageInfo_TrackUpdateReq_Item proto.InternalMessageInfo

func (m *TrackUpdateReq_Item) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

// TrackListReq 运单列表请求
type TrackListReq struct {
	Number               string       `protobuf:"bytes,1,opt,name=number,proto3" json:"number" form:"number"`
	Carrier              int32        `protobuf:"varint,2,opt,name=carrier,proto3" json:"carrier" form:"carrier"`
	RegisteTimeFrom      string       `protobuf:"bytes,3,opt,name=registe_time_from,json=registeTimeFrom,proto3" json:"registe_time_from" form:"registe_time_from"`
	RegisteTimeTo        string       `protobuf:"bytes,4,opt,name=registe_time_to,json=registeTimeTo,proto3" json:"registe_time_to" form:"registe_time_to"`
	TrackingTimeFrom     string       `protobuf:"bytes,5,opt,name=tracking_time_from,json=trackingTimeFrom,proto3" json:"tracking_time_from" form:"tracking_time_from"`
	TrackingTimeTo       string       `protobuf:"bytes,6,opt,name=tracking_time_to,json=trackingTimeTo,proto3" json:"tracking_time_to" form:"tracking_time_to"`
	PushTimeFrom         string       `protobuf:"bytes,7,opt,name=push_time_from,json=pushTimeFrom,proto3" json:"push_time_from" form:"push_time_from"`
	PushTimeTo           string       `protobuf:"bytes,8,opt,name=push_time_to,json=pushTimeTo,proto3" json:"push_time_to" form:"push_time_to"`
	PushState            PushState    `protobuf:"varint,9,opt,name=push_state,json=pushState,proto3,enum=track17.PushState" json:"push_state" form:"push_state"`
	StopTimeFrom         string       `protobuf:"bytes,10,opt,name=stop_time_from,json=stopTimeFrom,proto3" json:"stop_time_from" form:"stop_time_from"`
	StopTimeTo           string       `protobuf:"bytes,11,opt,name=stop_time_to,json=stopTimeTo,proto3" json:"stop_time_to" form:"stop_time_to"`
	PackageState         PackageState `protobuf:"varint,12,opt,name=package_state,json=packageState,proto3,enum=track17.PackageState" json:"package_state" form:"package_state"`
	PageNo               int32        `protobuf:"varint,13,opt,name=page_no,json=pageNo,proto3" json:"page_no" form:"page_no"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *TrackListReq) Reset()         { *m = TrackListReq{} }
func (m *TrackListReq) String() string { return proto.CompactTextString(m) }
func (*TrackListReq) ProtoMessage()    {}
func (*TrackListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_7603acb2f1f18262, []int{8}
}

func (m *TrackListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrackListReq.Unmarshal(m, b)
}
func (m *TrackListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrackListReq.Marshal(b, m, deterministic)
}
func (m *TrackListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrackListReq.Merge(m, src)
}
func (m *TrackListReq) XXX_Size() int {
	return xxx_messageInfo_TrackListReq.Size(m)
}
func (m *TrackListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_TrackListReq.DiscardUnknown(m)
}

var xxx_messageInfo_TrackListReq proto.InternalMessageInfo

func (m *TrackListReq) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *TrackListReq) GetCarrier() int32 {
	if m != nil {
		return m.Carrier
	}
	return 0
}

func (m *TrackListReq) GetRegisteTimeFrom() string {
	if m != nil {
		return m.RegisteTimeFrom
	}
	return ""
}

func (m *TrackListReq) GetRegisteTimeTo() string {
	if m != nil {
		return m.RegisteTimeTo
	}
	return ""
}

func (m *TrackListReq) GetTrackingTimeFrom() string {
	if m != nil {
		return m.TrackingTimeFrom
	}
	return ""
}

func (m *TrackListReq) GetTrackingTimeTo() string {
	if m != nil {
		return m.TrackingTimeTo
	}
	return ""
}

func (m *TrackListReq) GetPushTimeFrom() string {
	if m != nil {
		return m.PushTimeFrom
	}
	return ""
}

func (m *TrackListReq) GetPushTimeTo() string {
	if m != nil {
		return m.PushTimeTo
	}
	return ""
}

func (m *TrackListReq) GetPushState() PushState {
	if m != nil {
		return m.PushState
	}
	return PushState_PS_NOT_PUSH
}

func (m *TrackListReq) GetStopTimeFrom() string {
	if m != nil {
		return m.StopTimeFrom
	}
	return ""
}

func (m *TrackListReq) GetStopTimeTo() string {
	if m != nil {
		return m.StopTimeTo
	}
	return ""
}

func (m *TrackListReq) GetPackageState() PackageState {
	if m != nil {
		return m.PackageState
	}
	return PackageState_PKGS_NOTFOUND
}

func (m *TrackListReq) GetPageNo() int32 {
	if m != nil {
		return m.PageNo
	}
	return 0
}

// TrackListResp 运单列表返回
type TrackListResp struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code" form:"code"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TrackListResp) Reset()         { *m = TrackListResp{} }
func (m *TrackListResp) String() string { return proto.CompactTextString(m) }
func (*TrackListResp) ProtoMessage()    {}
func (*TrackListResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_7603acb2f1f18262, []int{9}
}

func (m *TrackListResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrackListResp.Unmarshal(m, b)
}
func (m *TrackListResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrackListResp.Marshal(b, m, deterministic)
}
func (m *TrackListResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrackListResp.Merge(m, src)
}
func (m *TrackListResp) XXX_Size() int {
	return xxx_messageInfo_TrackListResp.Size(m)
}
func (m *TrackListResp) XXX_DiscardUnknown() {
	xxx_messageInfo_TrackListResp.DiscardUnknown(m)
}

var xxx_messageInfo_TrackListResp proto.InternalMessageInfo

func (m *TrackListResp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

type TrackListResp_Data struct {
	Accepted             *TrackListResp_Data_Accepted `protobuf:"bytes,1,opt,name=accepted,proto3" json:"accepted" form:"accepted"`
	Rejected             *TrackReject                 `protobuf:"bytes,2,opt,name=rejected,proto3" json:"rejected" form:"rejected"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *TrackListResp_Data) Reset()         { *m = TrackListResp_Data{} }
func (m *TrackListResp_Data) String() string { return proto.CompactTextString(m) }
func (*TrackListResp_Data) ProtoMessage()    {}
func (*TrackListResp_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_7603acb2f1f18262, []int{9, 0}
}

func (m *TrackListResp_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrackListResp_Data.Unmarshal(m, b)
}
func (m *TrackListResp_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrackListResp_Data.Marshal(b, m, deterministic)
}
func (m *TrackListResp_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrackListResp_Data.Merge(m, src)
}
func (m *TrackListResp_Data) XXX_Size() int {
	return xxx_messageInfo_TrackListResp_Data.Size(m)
}
func (m *TrackListResp_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_TrackListResp_Data.DiscardUnknown(m)
}

var xxx_messageInfo_TrackListResp_Data proto.InternalMessageInfo

func (m *TrackListResp_Data) GetAccepted() *TrackListResp_Data_Accepted {
	if m != nil {
		return m.Accepted
	}
	return nil
}

func (m *TrackListResp_Data) GetRejected() *TrackReject {
	if m != nil {
		return m.Rejected
	}
	return nil
}

type TrackListResp_Data_Accepted struct {
	Number               string          `protobuf:"bytes,1,opt,name=number,proto3" json:"number" form:"number"`
	W1                   int32           `protobuf:"varint,2,opt,name=w1,proto3" json:"w1" form:"w1"`
	W2                   int32           `protobuf:"varint,3,opt,name=w2,proto3" json:"w2" form:"w2"`
	B                    int32           `protobuf:"varint,4,opt,name=b,proto3" json:"b" form:"b"`
	C                    int32           `protobuf:"varint,5,opt,name=c,proto3" json:"c" form:"c"`
	E                    PackageState    `protobuf:"varint,6,opt,name=e,proto3,enum=track17.PackageState" json:"e" form:"e"`
	Rt                   string          `protobuf:"bytes,7,opt,name=rt,proto3" json:"rt" form:"rt"`
	Tt                   string          `protobuf:"bytes,8,opt,name=tt,proto3" json:"tt" form:"tt"`
	Pt                   string          `protobuf:"bytes,9,opt,name=pt,proto3" json:"pt" form:"pt"`
	Ps                   int32           `protobuf:"varint,10,opt,name=ps,proto3" json:"ps" form:"ps"`
	St                   string          `protobuf:"bytes,11,opt,name=st,proto3" json:"st" form:"st"`
	Sr                   StopTrackReason `protobuf:"varint,12,opt,name=sr,proto3,enum=track17.StopTrackReason" json:"sr" form:"sr"`
	Ir                   bool            `protobuf:"varint,13,opt,name=ir,proto3" json:"ir" form:"ir"`
	Ts                   bool            `protobuf:"varint,14,opt,name=ts,proto3" json:"ts" form:"ts"`
	Mc                   int32           `protobuf:"varint,15,opt,name=mc,proto3" json:"mc" form:"mc"`
	Tag                  string          `protobuf:"bytes,16,opt,name=tag,proto3" json:"tag" form:"tag"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *TrackListResp_Data_Accepted) Reset()         { *m = TrackListResp_Data_Accepted{} }
func (m *TrackListResp_Data_Accepted) String() string { return proto.CompactTextString(m) }
func (*TrackListResp_Data_Accepted) ProtoMessage()    {}
func (*TrackListResp_Data_Accepted) Descriptor() ([]byte, []int) {
	return fileDescriptor_7603acb2f1f18262, []int{9, 0, 0}
}

func (m *TrackListResp_Data_Accepted) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrackListResp_Data_Accepted.Unmarshal(m, b)
}
func (m *TrackListResp_Data_Accepted) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrackListResp_Data_Accepted.Marshal(b, m, deterministic)
}
func (m *TrackListResp_Data_Accepted) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrackListResp_Data_Accepted.Merge(m, src)
}
func (m *TrackListResp_Data_Accepted) XXX_Size() int {
	return xxx_messageInfo_TrackListResp_Data_Accepted.Size(m)
}
func (m *TrackListResp_Data_Accepted) XXX_DiscardUnknown() {
	xxx_messageInfo_TrackListResp_Data_Accepted.DiscardUnknown(m)
}

var xxx_messageInfo_TrackListResp_Data_Accepted proto.InternalMessageInfo

func (m *TrackListResp_Data_Accepted) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *TrackListResp_Data_Accepted) GetW1() int32 {
	if m != nil {
		return m.W1
	}
	return 0
}

func (m *TrackListResp_Data_Accepted) GetW2() int32 {
	if m != nil {
		return m.W2
	}
	return 0
}

func (m *TrackListResp_Data_Accepted) GetB() int32 {
	if m != nil {
		return m.B
	}
	return 0
}

func (m *TrackListResp_Data_Accepted) GetC() int32 {
	if m != nil {
		return m.C
	}
	return 0
}

func (m *TrackListResp_Data_Accepted) GetE() PackageState {
	if m != nil {
		return m.E
	}
	return PackageState_PKGS_NOTFOUND
}

func (m *TrackListResp_Data_Accepted) GetRt() string {
	if m != nil {
		return m.Rt
	}
	return ""
}

func (m *TrackListResp_Data_Accepted) GetTt() string {
	if m != nil {
		return m.Tt
	}
	return ""
}

func (m *TrackListResp_Data_Accepted) GetPt() string {
	if m != nil {
		return m.Pt
	}
	return ""
}

func (m *TrackListResp_Data_Accepted) GetPs() int32 {
	if m != nil {
		return m.Ps
	}
	return 0
}

func (m *TrackListResp_Data_Accepted) GetSt() string {
	if m != nil {
		return m.St
	}
	return ""
}

func (m *TrackListResp_Data_Accepted) GetSr() StopTrackReason {
	if m != nil {
		return m.Sr
	}
	return StopTrackReason_STR_UNKNOWN
}

func (m *TrackListResp_Data_Accepted) GetIr() bool {
	if m != nil {
		return m.Ir
	}
	return false
}

func (m *TrackListResp_Data_Accepted) GetTs() bool {
	if m != nil {
		return m.Ts
	}
	return false
}

func (m *TrackListResp_Data_Accepted) GetMc() int32 {
	if m != nil {
		return m.Mc
	}
	return 0
}

func (m *TrackListResp_Data_Accepted) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

// 物流详情
type TrackInfo struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code" form:"code"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TrackInfo) Reset()         { *m = TrackInfo{} }
func (m *TrackInfo) String() string { return proto.CompactTextString(m) }
func (*TrackInfo) ProtoMessage()    {}
func (*TrackInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_7603acb2f1f18262, []int{10}
}

func (m *TrackInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrackInfo.Unmarshal(m, b)
}
func (m *TrackInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrackInfo.Marshal(b, m, deterministic)
}
func (m *TrackInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrackInfo.Merge(m, src)
}
func (m *TrackInfo) XXX_Size() int {
	return xxx_messageInfo_TrackInfo.Size(m)
}
func (m *TrackInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_TrackInfo.DiscardUnknown(m)
}

var xxx_messageInfo_TrackInfo proto.InternalMessageInfo

func (m *TrackInfo) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

type TrackInfo_Data struct {
	Accepted             []*TrackInfo_Data_Accepted `protobuf:"bytes,1,rep,name=accepted,proto3" json:"accepted" form:"accepted"`
	Rejected             []*TrackReject             `protobuf:"bytes,2,rep,name=rejected,proto3" json:"rejected" form:"rejected"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *TrackInfo_Data) Reset()         { *m = TrackInfo_Data{} }
func (m *TrackInfo_Data) String() string { return proto.CompactTextString(m) }
func (*TrackInfo_Data) ProtoMessage()    {}
func (*TrackInfo_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_7603acb2f1f18262, []int{10, 0}
}

func (m *TrackInfo_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrackInfo_Data.Unmarshal(m, b)
}
func (m *TrackInfo_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrackInfo_Data.Marshal(b, m, deterministic)
}
func (m *TrackInfo_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrackInfo_Data.Merge(m, src)
}
func (m *TrackInfo_Data) XXX_Size() int {
	return xxx_messageInfo_TrackInfo_Data.Size(m)
}
func (m *TrackInfo_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_TrackInfo_Data.DiscardUnknown(m)
}

var xxx_messageInfo_TrackInfo_Data proto.InternalMessageInfo

func (m *TrackInfo_Data) GetAccepted() []*TrackInfo_Data_Accepted {
	if m != nil {
		return m.Accepted
	}
	return nil
}

func (m *TrackInfo_Data) GetRejected() []*TrackReject {
	if m != nil {
		return m.Rejected
	}
	return nil
}

type TrackInfo_Data_Accepted struct {
	Number               string   `protobuf:"bytes,1,opt,name=number,proto3" json:"number" form:"number"`
	Tag                  string   `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag" form:"tag"`
	Track                *Track   `protobuf:"bytes,3,opt,name=track,proto3" json:"track" form:"track"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TrackInfo_Data_Accepted) Reset()         { *m = TrackInfo_Data_Accepted{} }
func (m *TrackInfo_Data_Accepted) String() string { return proto.CompactTextString(m) }
func (*TrackInfo_Data_Accepted) ProtoMessage()    {}
func (*TrackInfo_Data_Accepted) Descriptor() ([]byte, []int) {
	return fileDescriptor_7603acb2f1f18262, []int{10, 0, 0}
}

func (m *TrackInfo_Data_Accepted) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrackInfo_Data_Accepted.Unmarshal(m, b)
}
func (m *TrackInfo_Data_Accepted) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrackInfo_Data_Accepted.Marshal(b, m, deterministic)
}
func (m *TrackInfo_Data_Accepted) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrackInfo_Data_Accepted.Merge(m, src)
}
func (m *TrackInfo_Data_Accepted) XXX_Size() int {
	return xxx_messageInfo_TrackInfo_Data_Accepted.Size(m)
}
func (m *TrackInfo_Data_Accepted) XXX_DiscardUnknown() {
	xxx_messageInfo_TrackInfo_Data_Accepted.DiscardUnknown(m)
}

var xxx_messageInfo_TrackInfo_Data_Accepted proto.InternalMessageInfo

func (m *TrackInfo_Data_Accepted) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *TrackInfo_Data_Accepted) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *TrackInfo_Data_Accepted) GetTrack() *Track {
	if m != nil {
		return m.Track
	}
	return nil
}

// 追踪详情
type Track struct {
	W1                   int32         `protobuf:"varint,1,opt,name=w1,proto3" json:"w1" form:"w1"`
	W2                   int32         `protobuf:"varint,2,opt,name=w2,proto3" json:"w2" form:"w2"`
	B                    int32         `protobuf:"varint,3,opt,name=b,proto3" json:"b" form:"b"`
	C                    int32         `protobuf:"varint,4,opt,name=c,proto3" json:"c" form:"c"`
	E                    PackageState  `protobuf:"varint,5,opt,name=e,proto3,enum=track17.PackageState" json:"e" form:"e"`
	F                    int32         `protobuf:"varint,6,opt,name=f,proto3" json:"f" form:"f"`
	Z0                   *TrackEvent   `protobuf:"bytes,7,opt,name=z0,proto3" json:"z0" form:"z0"`
	Z1                   []*TrackEvent `protobuf:"bytes,8,rep,name=z1,proto3" json:"z1" form:"z1"`
	Z2                   []*TrackEvent `protobuf:"bytes,9,rep,name=z2,proto3" json:"z2" form:"z2"`
	Z9                   []*TrackEvent `protobuf:"bytes,10,rep,name=z9,proto3" json:"z9" form:"z9"`
	Ygt1                 int32         `protobuf:"varint,11,opt,name=ygt1,proto3" json:"ygt1" form:"ygt1"`
	Ygt2                 int32         `protobuf:"varint,12,opt,name=ygt2,proto3" json:"ygt2" form:"ygt2"`
	Ygt9                 int32         `protobuf:"varint,13,opt,name=ygt9,proto3" json:"ygt9" form:"ygt9"`
	Ylt1                 string        `protobuf:"bytes,14,opt,name=ylt1,proto3" json:"ylt1" form:"ylt1"`
	Ylt2                 string        `protobuf:"bytes,15,opt,name=ylt2,proto3" json:"ylt2" form:"ylt2"`
	Ylt9                 string        `protobuf:"bytes,16,opt,name=ylt9,proto3" json:"ylt9" form:"ylt9"`
	Is1                  CarrierState  `protobuf:"varint,17,opt,name=is1,proto3,enum=track17.CarrierState" json:"is1" form:"is1"`
	Is2                  CarrierState  `protobuf:"varint,18,opt,name=is2,proto3,enum=track17.CarrierState" json:"is2" form:"is2"`
	Ln1                  string        `protobuf:"bytes,19,opt,name=ln1,proto3" json:"ln1" form:"ln1"`
	Ln2                  string        `protobuf:"bytes,20,opt,name=ln2,proto3" json:"ln2" form:"ln2"`
	Ln9                  string        `protobuf:"bytes,21,opt,name=ln9,proto3" json:"ln9" form:"ln9"`
	Hs                   int32         `protobuf:"varint,22,opt,name=hs,proto3" json:"hs" form:"hs"`
	Yt                   string        `protobuf:"bytes,23,opt,name=yt,proto3" json:"yt" form:"yt"`
	Zex                  *TrackExpand  `protobuf:"bytes,24,opt,name=zex,proto3" json:"zex" form:"zex"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Track) Reset()         { *m = Track{} }
func (m *Track) String() string { return proto.CompactTextString(m) }
func (*Track) ProtoMessage()    {}
func (*Track) Descriptor() ([]byte, []int) {
	return fileDescriptor_7603acb2f1f18262, []int{11}
}

func (m *Track) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Track.Unmarshal(m, b)
}
func (m *Track) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Track.Marshal(b, m, deterministic)
}
func (m *Track) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Track.Merge(m, src)
}
func (m *Track) XXX_Size() int {
	return xxx_messageInfo_Track.Size(m)
}
func (m *Track) XXX_DiscardUnknown() {
	xxx_messageInfo_Track.DiscardUnknown(m)
}

var xxx_messageInfo_Track proto.InternalMessageInfo

func (m *Track) GetW1() int32 {
	if m != nil {
		return m.W1
	}
	return 0
}

func (m *Track) GetW2() int32 {
	if m != nil {
		return m.W2
	}
	return 0
}

func (m *Track) GetB() int32 {
	if m != nil {
		return m.B
	}
	return 0
}

func (m *Track) GetC() int32 {
	if m != nil {
		return m.C
	}
	return 0
}

func (m *Track) GetE() PackageState {
	if m != nil {
		return m.E
	}
	return PackageState_PKGS_NOTFOUND
}

func (m *Track) GetF() int32 {
	if m != nil {
		return m.F
	}
	return 0
}

func (m *Track) GetZ0() *TrackEvent {
	if m != nil {
		return m.Z0
	}
	return nil
}

func (m *Track) GetZ1() []*TrackEvent {
	if m != nil {
		return m.Z1
	}
	return nil
}

func (m *Track) GetZ2() []*TrackEvent {
	if m != nil {
		return m.Z2
	}
	return nil
}

func (m *Track) GetZ9() []*TrackEvent {
	if m != nil {
		return m.Z9
	}
	return nil
}

func (m *Track) GetYgt1() int32 {
	if m != nil {
		return m.Ygt1
	}
	return 0
}

func (m *Track) GetYgt2() int32 {
	if m != nil {
		return m.Ygt2
	}
	return 0
}

func (m *Track) GetYgt9() int32 {
	if m != nil {
		return m.Ygt9
	}
	return 0
}

func (m *Track) GetYlt1() string {
	if m != nil {
		return m.Ylt1
	}
	return ""
}

func (m *Track) GetYlt2() string {
	if m != nil {
		return m.Ylt2
	}
	return ""
}

func (m *Track) GetYlt9() string {
	if m != nil {
		return m.Ylt9
	}
	return ""
}

func (m *Track) GetIs1() CarrierState {
	if m != nil {
		return m.Is1
	}
	return CarrierState_CS_UNRECOGNIZED
}

func (m *Track) GetIs2() CarrierState {
	if m != nil {
		return m.Is2
	}
	return CarrierState_CS_UNRECOGNIZED
}

func (m *Track) GetLn1() string {
	if m != nil {
		return m.Ln1
	}
	return ""
}

func (m *Track) GetLn2() string {
	if m != nil {
		return m.Ln2
	}
	return ""
}

func (m *Track) GetLn9() string {
	if m != nil {
		return m.Ln9
	}
	return ""
}

func (m *Track) GetHs() int32 {
	if m != nil {
		return m.Hs
	}
	return 0
}

func (m *Track) GetYt() string {
	if m != nil {
		return m.Yt
	}
	return ""
}

func (m *Track) GetZex() *TrackExpand {
	if m != nil {
		return m.Zex
	}
	return nil
}

// 追踪扩展
type TrackExpand struct {
	TrC                  string   `protobuf:"bytes,1,opt,name=trC,proto3" json:"trC" form:"trC"`
	TrN                  string   `protobuf:"bytes,2,opt,name=trN,proto3" json:"trN" form:"trN"`
	DtS                  string   `protobuf:"bytes,3,opt,name=dtS,proto3" json:"dtS" form:"dtS"`
	DtP                  string   `protobuf:"bytes,4,opt,name=dtP,proto3" json:"dtP" form:"dtP"`
	DtD                  string   `protobuf:"bytes,5,opt,name=dtD,proto3" json:"dtD" form:"dtD"`
	DtL                  string   `protobuf:"bytes,6,opt,name=dtL,proto3" json:"dtL" form:"dtL"`
	Dt                   string   `protobuf:"bytes,7,opt,name=dt,proto3" json:"dt" form:"dt"`
	Psex                 string   `protobuf:"bytes,8,opt,name=psex,proto3" json:"psex" form:"psex"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TrackExpand) Reset()         { *m = TrackExpand{} }
func (m *TrackExpand) String() string { return proto.CompactTextString(m) }
func (*TrackExpand) ProtoMessage()    {}
func (*TrackExpand) Descriptor() ([]byte, []int) {
	return fileDescriptor_7603acb2f1f18262, []int{12}
}

func (m *TrackExpand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrackExpand.Unmarshal(m, b)
}
func (m *TrackExpand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrackExpand.Marshal(b, m, deterministic)
}
func (m *TrackExpand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrackExpand.Merge(m, src)
}
func (m *TrackExpand) XXX_Size() int {
	return xxx_messageInfo_TrackExpand.Size(m)
}
func (m *TrackExpand) XXX_DiscardUnknown() {
	xxx_messageInfo_TrackExpand.DiscardUnknown(m)
}

var xxx_messageInfo_TrackExpand proto.InternalMessageInfo

func (m *TrackExpand) GetTrC() string {
	if m != nil {
		return m.TrC
	}
	return ""
}

func (m *TrackExpand) GetTrN() string {
	if m != nil {
		return m.TrN
	}
	return ""
}

func (m *TrackExpand) GetDtS() string {
	if m != nil {
		return m.DtS
	}
	return ""
}

func (m *TrackExpand) GetDtP() string {
	if m != nil {
		return m.DtP
	}
	return ""
}

func (m *TrackExpand) GetDtD() string {
	if m != nil {
		return m.DtD
	}
	return ""
}

func (m *TrackExpand) GetDtL() string {
	if m != nil {
		return m.DtL
	}
	return ""
}

func (m *TrackExpand) GetDt() string {
	if m != nil {
		return m.Dt
	}
	return ""
}

func (m *TrackExpand) GetPsex() string {
	if m != nil {
		return m.Psex
	}
	return ""
}

// 追踪事件
type TrackEvent struct {
	A                    string   `protobuf:"bytes,1,opt,name=a,proto3" json:"a" form:"a"`
	B                    string   `protobuf:"bytes,2,opt,name=b,proto3" json:"b" form:"b"`
	C                    string   `protobuf:"bytes,3,opt,name=c,proto3" json:"c" form:"c"`
	D                    string   `protobuf:"bytes,4,opt,name=d,proto3" json:"d" form:"d"`
	Z                    string   `protobuf:"bytes,5,opt,name=z,proto3" json:"z" form:"z"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TrackEvent) Reset()         { *m = TrackEvent{} }
func (m *TrackEvent) String() string { return proto.CompactTextString(m) }
func (*TrackEvent) ProtoMessage()    {}
func (*TrackEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_7603acb2f1f18262, []int{13}
}

func (m *TrackEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrackEvent.Unmarshal(m, b)
}
func (m *TrackEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrackEvent.Marshal(b, m, deterministic)
}
func (m *TrackEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrackEvent.Merge(m, src)
}
func (m *TrackEvent) XXX_Size() int {
	return xxx_messageInfo_TrackEvent.Size(m)
}
func (m *TrackEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_TrackEvent.DiscardUnknown(m)
}

var xxx_messageInfo_TrackEvent proto.InternalMessageInfo

func (m *TrackEvent) GetA() string {
	if m != nil {
		return m.A
	}
	return ""
}

func (m *TrackEvent) GetB() string {
	if m != nil {
		return m.B
	}
	return ""
}

func (m *TrackEvent) GetC() string {
	if m != nil {
		return m.C
	}
	return ""
}

func (m *TrackEvent) GetD() string {
	if m != nil {
		return m.D
	}
	return ""
}

func (m *TrackEvent) GetZ() string {
	if m != nil {
		return m.Z
	}
	return ""
}

func init() {
	proto.RegisterEnum("track17.PushState", PushState_name, PushState_value)
	proto.RegisterEnum("track17.CarrierState", CarrierState_name, CarrierState_value)
	proto.RegisterEnum("track17.PackageState", PackageState_name, PackageState_value)
	proto.RegisterEnum("track17.TrackState", TrackState_name, TrackState_value)
	proto.RegisterEnum("track17.StopTrackReason", StopTrackReason_name, StopTrackReason_value)
	proto.RegisterType((*Error)(nil), "track17.Error")
	proto.RegisterType((*Error_ErrorData)(nil), "track17.Error.ErrorData")
	proto.RegisterType((*RejectError)(nil), "track17.RejectError")
	proto.RegisterType((*TrackAccept)(nil), "track17.TrackAccept")
	proto.RegisterType((*TrackReject)(nil), "track17.TrackReject")
	proto.RegisterType((*TrackReq)(nil), "track17.TrackReq")
	proto.RegisterType((*TrackResp)(nil), "track17.TrackResp")
	proto.RegisterType((*TrackResp_Data)(nil), "track17.TrackResp.Data")
	proto.RegisterType((*ChangeCarrierReq)(nil), "track17.ChangeCarrierReq")
	proto.RegisterType((*TrackUpdateReq)(nil), "track17.TrackUpdateReq")
	proto.RegisterType((*TrackUpdateReq_Item)(nil), "track17.TrackUpdateReq.Item")
	proto.RegisterType((*TrackListReq)(nil), "track17.TrackListReq")
	proto.RegisterType((*TrackListResp)(nil), "track17.TrackListResp")
	proto.RegisterType((*TrackListResp_Data)(nil), "track17.TrackListResp.Data")
	proto.RegisterType((*TrackListResp_Data_Accepted)(nil), "track17.TrackListResp.Data.Accepted")
	proto.RegisterType((*TrackInfo)(nil), "track17.TrackInfo")
	proto.RegisterType((*TrackInfo_Data)(nil), "track17.TrackInfo.Data")
	proto.RegisterType((*TrackInfo_Data_Accepted)(nil), "track17.TrackInfo.Data.Accepted")
	proto.RegisterType((*Track)(nil), "track17.Track")
	proto.RegisterType((*TrackExpand)(nil), "track17.TrackExpand")
	proto.RegisterType((*TrackEvent)(nil), "track17.TrackEvent")
}

func init() { proto.RegisterFile("17track.proto", fileDescriptor_7603acb2f1f18262) }

var fileDescriptor_7603acb2f1f18262 = []byte{
	// 1538 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x57, 0xcb, 0x6e, 0xdb, 0x46,
	0x14, 0xcd, 0x50, 0x92, 0x6d, 0x5d, 0x3d, 0x4c, 0x8f, 0x5f, 0xac, 0x11, 0xb4, 0x82, 0x9c, 0xa6,
	0xaa, 0x1a, 0x18, 0x11, 0xbb, 0x08, 0xdc, 0x66, 0x51, 0x95, 0xa2, 0x1d, 0x22, 0x2e, 0xa5, 0x0e,
	0xa9, 0xa4, 0xc8, 0x86, 0xa0, 0x25, 0x5a, 0x56, 0x62, 0x89, 0x2a, 0x39, 0xae, 0x13, 0xaf, 0xbb,
	0x2d, 0xd0, 0x75, 0x81, 0xf6, 0x3b, 0xba, 0x28, 0xd0, 0x4d, 0xf7, 0x05, 0xf2, 0x09, 0xfd, 0x86,
	0x7e, 0x40, 0x31, 0x0f, 0xd2, 0x94, 0x1f, 0x49, 0x9a, 0x8d, 0x31, 0xf7, 0xf0, 0xcc, 0x99, 0x3b,
	0xf7, 0x9e, 0x99, 0x91, 0xa1, 0xd2, 0x7a, 0x40, 0x23, 0x7f, 0xf0, 0x62, 0x67, 0x16, 0x85, 0x34,
	0xc4, 0x8b, 0x3c, 0x68, 0x3d, 0xa8, 0xff, 0x86, 0xa0, 0x60, 0x46, 0x51, 0x18, 0x61, 0x0c, 0xf9,
	0x41, 0x38, 0x0c, 0x34, 0x54, 0x43, 0x8d, 0x02, 0xe1, 0x63, 0xac, 0xc1, 0xe2, 0x24, 0x88, 0x63,
	0x7f, 0x14, 0x68, 0x4a, 0x0d, 0x35, 0x8a, 0x24, 0x09, 0xf1, 0x3d, 0xc8, 0x0f, 0x7d, 0xea, 0x6b,
	0xb9, 0x1a, 0x6a, 0x94, 0x74, 0x6d, 0x47, 0xea, 0xed, 0x70, 0x2d, 0xf1, 0xb7, 0xe3, 0x53, 0x9f,
	0x70, 0xd6, 0xd6, 0x2e, 0x14, 0x53, 0x08, 0xdf, 0x83, 0x85, 0x80, 0x05, 0xb1, 0x86, 0x6a, 0xb9,
	0x46, 0x49, 0x5f, 0x4b, 0x27, 0x93, 0xe0, 0x79, 0x30, 0xa0, 0x9c, 0x49, 0x24, 0xa7, 0xfe, 0x25,
	0x94, 0x32, 0xf0, 0xff, 0xcb, 0xb2, 0xfe, 0x14, 0x4a, 0x2e, 0xd3, 0x6e, 0x0f, 0x06, 0xc1, 0x8c,
	0xe2, 0x0d, 0x58, 0x08, 0xa3, 0xf1, 0x68, 0x3c, 0x95, 0xd3, 0x65, 0xc4, 0xf0, 0xe9, 0xe9, 0xe4,
	0x30, 0x88, 0xe4, 0x7c, 0x19, 0x31, 0xe1, 0x81, 0x1f, 0x45, 0xe3, 0x20, 0xe2, 0xfb, 0x2c, 0x90,
	0x24, 0xac, 0x7f, 0x2b, 0x85, 0x45, 0x6a, 0x19, 0x01, 0x34, 0x27, 0xd0, 0x84, 0x02, 0xdf, 0x06,
	0xd7, 0xbd, 0x69, 0xa7, 0x82, 0x52, 0xff, 0x05, 0xc1, 0x92, 0xd4, 0xfc, 0xfe, 0x46, 0xc1, 0x4c,
	0x46, 0xca, 0x5c, 0x46, 0x78, 0x1b, 0x2a, 0x47, 0xe3, 0xa9, 0x7f, 0xe2, 0xcd, 0x67, 0x5c, 0xe6,
	0xa0, 0x21, 0x49, 0x1f, 0x43, 0xd5, 0x3f, 0xa5, 0xa1, 0x37, 0x0c, 0x68, 0x30, 0xa0, 0xe3, 0x70,
	0xaa, 0xe5, 0x6b, 0xa8, 0xb1, 0x44, 0x2a, 0x0c, 0xed, 0x24, 0x20, 0x56, 0x21, 0x47, 0xfd, 0x91,
	0x56, 0xe0, 0x4b, 0xb3, 0x61, 0xfd, 0x77, 0x04, 0x45, 0x99, 0x5c, 0x3c, 0xbb, 0xb6, 0x09, 0x9f,
	0x49, 0x43, 0x88, 0x9d, 0x6e, 0xa6, 0x3b, 0x4d, 0x67, 0xed, 0x64, 0xfc, 0xf0, 0x1c, 0xf2, 0xdc,
	0x0a, 0xf7, 0x61, 0xc9, 0xe7, 0xad, 0x09, 0x86, 0x57, 0xcc, 0x90, 0x69, 0x1c, 0x49, 0x59, 0x6c,
	0x46, 0xc4, 0x6b, 0x17, 0x0c, 0x35, 0xe5, 0xba, 0x19, 0xa2, 0xb2, 0x24, 0x65, 0xd5, 0xff, 0x42,
	0xa0, 0x1a, 0xc7, 0xfe, 0x74, 0x14, 0xc8, 0x2a, 0xbc, 0xa9, 0xbe, 0x1f, 0x41, 0x49, 0xd6, 0xcf,
	0x0b, 0x4f, 0x86, 0xb2, 0xc6, 0x20, 0xa1, 0xee, 0xc9, 0x30, 0x4b, 0x98, 0x06, 0x67, 0xb2, 0xc8,
	0x09, 0xc1, 0x0e, 0xce, 0x70, 0x13, 0x56, 0xe6, 0xfa, 0xc0, 0x75, 0xf2, 0x9c, 0xb6, 0x9c, 0xed,
	0x05, 0x13, 0xbb, 0xc2, 0x65, 0x92, 0x85, 0xab, 0x5c, 0x3b, 0x38, 0xab, 0xff, 0x8c, 0xa0, 0xca,
	0x37, 0xd8, 0x9f, 0x0d, 0x7d, 0x1a, 0xbc, 0x9f, 0x49, 0x74, 0x28, 0x8c, 0x69, 0x30, 0x89, 0xe5,
	0xb1, 0xbd, 0x3d, 0x5f, 0xba, 0x54, 0x79, 0xc7, 0xa2, 0xc1, 0x84, 0x08, 0xea, 0x96, 0x06, 0x79,
	0x16, 0x26, 0xa6, 0x40, 0x17, 0xa6, 0xf8, 0x31, 0x0f, 0x65, 0x3e, 0xf1, 0x60, 0x1c, 0xd3, 0xf7,
	0x4b, 0xa8, 0x09, 0x2b, 0x51, 0x30, 0x1a, 0xc7, 0x34, 0xf0, 0xe8, 0x78, 0x12, 0x78, 0x47, 0x51,
	0x38, 0xe1, 0xc9, 0x15, 0xc9, 0xb2, 0xfc, 0xe0, 0x8e, 0x27, 0xc1, 0x5e, 0x14, 0x4e, 0xf0, 0x5d,
	0x58, 0x9e, 0xe3, 0xd2, 0x90, 0xd7, 0xb5, 0x48, 0x2a, 0x19, 0xa6, 0x1b, 0xe2, 0x7b, 0x80, 0xf9,
	0xb6, 0xc6, 0xd3, 0x51, 0x46, 0x54, 0x98, 0x59, 0x4d, 0xbe, 0xa4, 0xaa, 0x0d, 0x50, 0xe7, 0xd9,
	0x34, 0xd4, 0x16, 0x38, 0xb7, 0x9a, 0xe5, 0xba, 0x21, 0xbe, 0x03, 0xd5, 0xd9, 0x69, 0x7c, 0x9c,
	0xd1, 0x5c, 0xe4, 0xbc, 0x32, 0x43, 0x53, 0xbd, 0x1a, 0x94, 0x2f, 0x58, 0x34, 0xd4, 0x96, 0x38,
	0x07, 0x12, 0x8e, 0x1b, 0xe2, 0x16, 0xf0, 0xc8, 0x8b, 0xa9, 0x4f, 0x03, 0xad, 0x58, 0x43, 0x8d,
	0xaa, 0x8e, 0xd3, 0x4e, 0xf4, 0x4e, 0xe3, 0x63, 0x87, 0x7d, 0x21, 0xc5, 0x59, 0x32, 0x64, 0x4b,
	0xc7, 0x34, 0x9c, 0x65, 0x96, 0x06, 0xb1, 0x34, 0x43, 0xb3, 0x4b, 0x5f, 0xb0, 0x68, 0xa8, 0x95,
	0xc4, 0xd2, 0x09, 0xc7, 0x0d, 0xf1, 0x17, 0x50, 0x99, 0xf9, 0x83, 0x17, 0xfe, 0x28, 0x90, 0xab,
	0x97, 0xf9, 0xea, 0xeb, 0x17, 0xab, 0x8b, 0xaf, 0x22, 0x81, 0xf2, 0x2c, 0x13, 0xe1, 0x4d, 0x58,
	0x9c, 0xb1, 0x89, 0xd3, 0x50, 0xab, 0x88, 0xdb, 0x93, 0x85, 0x76, 0x58, 0xff, 0x27, 0x07, 0x95,
	0x8c, 0x0d, 0xae, 0xbf, 0x1f, 0xb6, 0xfe, 0xc8, 0xc9, 0x33, 0xff, 0xd5, 0xdc, 0x99, 0x67, 0x36,
	0xbc, 0x33, 0x6f, 0xc3, 0x44, 0x86, 0x5f, 0x18, 0x3b, 0x6d, 0xc9, 0xbd, 0xf1, 0x0e, 0x40, 0x6f,
	0xbf, 0x03, 0xb6, 0xfe, 0x54, 0x60, 0x29, 0x11, 0xba, 0xd1, 0xa5, 0x55, 0x50, 0xce, 0x5a, 0xd2,
	0xa0, 0xca, 0x59, 0x8b, 0xc7, 0xba, 0x3c, 0xe1, 0xca, 0x99, 0x8e, 0xcb, 0x80, 0x0e, 0xe5, 0x49,
	0x46, 0x87, 0x2c, 0x1a, 0xc8, 0xb3, 0x8a, 0x06, 0x78, 0x1b, 0x50, 0xc0, 0x6d, 0x73, 0x63, 0x31,
	0x51, 0xc0, 0x04, 0x23, 0x2a, 0x4d, 0xa3, 0x44, 0x94, 0xc5, 0x94, 0x4a, 0x83, 0x28, 0x94, 0xc7,
	0x33, 0xca, 0x0d, 0x51, 0x24, 0xca, 0x4c, 0xc4, 0x31, 0xef, 0x74, 0x81, 0x28, 0xb3, 0x98, 0xc5,
	0x31, 0x95, 0x5d, 0x55, 0x62, 0x8a, 0x1b, 0xa0, 0xc4, 0x91, 0x6c, 0xe1, 0xc5, 0x0b, 0xec, 0xb0,
	0x76, 0x8b, 0x2a, 0xf8, 0x71, 0x38, 0x25, 0x4a, 0xcc, 0xb7, 0x36, 0x8e, 0x78, 0xdb, 0x96, 0x88,
	0x32, 0xe6, 0x31, 0x8d, 0xb5, 0xaa, 0x88, 0x29, 0x57, 0x9e, 0x0c, 0xb4, 0x65, 0xb1, 0xd2, 0x64,
	0x90, 0x9c, 0x75, 0xf5, 0xe2, 0xac, 0xff, 0x9b, 0x3c, 0x00, 0xd6, 0xf4, 0x28, 0xbc, 0xb6, 0xc1,
	0xaf, 0x91, 0x6c, 0xf0, 0xc3, 0x2b, 0x97, 0x7a, 0x6d, 0xbe, 0x3d, 0x4c, 0xe2, 0x1d, 0x9b, 0xfb,
	0x0e, 0x17, 0xfc, 0xd6, 0xb3, 0x77, 0xe8, 0xad, 0xdc, 0x90, 0x92, 0x6e, 0x08, 0xdf, 0x81, 0x02,
	0x97, 0x95, 0x57, 0x61, 0xf5, 0xd2, 0x22, 0xe2, 0x63, 0xfd, 0x75, 0x1e, 0x0a, 0x1c, 0x90, 0xee,
	0x40, 0x97, 0xdc, 0xa1, 0xcc, 0xbb, 0x23, 0x37, 0xe7, 0x8e, 0xfc, 0x9c, 0x3b, 0x0a, 0x6f, 0x71,
	0x47, 0x19, 0xd0, 0x11, 0xb7, 0x50, 0x81, 0xa0, 0x23, 0xbc, 0x0d, 0xca, 0xf9, 0x7d, 0xee, 0x95,
	0x92, 0xbe, 0x3a, 0x9f, 0x9b, 0xf9, 0x43, 0x30, 0xa5, 0x44, 0x39, 0xbf, 0xcf, 0x49, 0x2d, 0x6d,
	0x89, 0x57, 0xe9, 0x06, 0x52, 0x8b, 0x93, 0x74, 0xad, 0xf8, 0x26, 0x92, 0xce, 0x49, 0xbb, 0x1a,
	0xbc, 0x89, 0xb4, 0xcb, 0xba, 0xfe, 0x6a, 0x44, 0x5b, 0xdc, 0x81, 0x05, 0xc2, 0xc7, 0x12, 0xd3,
	0xb9, 0x0b, 0x05, 0xa6, 0x4b, 0x6c, 0x57, 0x5e, 0x13, 0x7c, 0xcc, 0xb1, 0x13, 0xda, 0xe2, 0x9e,
	0x2b, 0x12, 0x3e, 0x96, 0x98, 0xce, 0x7d, 0x27, 0x30, 0x5d, 0x62, 0xbb, 0xd2, 0x7a, 0x7c, 0x8c,
	0x3f, 0x81, 0xdc, 0x38, 0x6e, 0x69, 0x2b, 0x97, 0x0a, 0x28, 0x1f, 0x47, 0x51, 0x40, 0xc6, 0x10,
	0x44, 0x5d, 0xc3, 0x6f, 0x21, 0xea, 0xcc, 0x0e, 0x27, 0xd3, 0x96, 0xb6, 0x2a, 0xec, 0x70, 0x32,
	0x6d, 0x09, 0x44, 0xd7, 0xd6, 0x12, 0x44, 0x72, 0x76, 0xb5, 0xf5, 0x04, 0xd9, 0x65, 0x2d, 0x3f,
	0x8e, 0xb5, 0x0d, 0xd1, 0xf2, 0x63, 0x7e, 0x6a, 0x5e, 0x51, 0x6d, 0x53, 0x9c, 0xc7, 0x57, 0x14,
	0xdf, 0x85, 0xdc, 0x79, 0xf0, 0x52, 0xd3, 0xae, 0xbb, 0x92, 0xcc, 0x97, 0x33, 0x7f, 0x3a, 0x24,
	0x8c, 0x50, 0xff, 0x15, 0xc9, 0x5f, 0x8f, 0x02, 0xe4, 0xe6, 0x8c, 0x8c, 0xf4, 0x65, 0x8d, 0x0c,
	0x81, 0xd8, 0xa9, 0x5d, 0x23, 0x9b, 0x21, 0x43, 0xea, 0xc8, 0xa7, 0x91, 0x0d, 0x05, 0xd2, 0x93,
	0x4f, 0x20, 0x1b, 0x0a, 0xa4, 0x93, 0xfc, 0x6c, 0x1b, 0xd2, 0x8e, 0x40, 0x0e, 0xe4, 0x7b, 0xc6,
	0x86, 0x2c, 0xe7, 0x61, 0x7a, 0x07, 0x0d, 0x29, 0xab, 0xf7, 0x2c, 0x0e, 0x5e, 0xca, 0x5b, 0x88,
	0x8f, 0xeb, 0x04, 0xe0, 0xa2, 0xf3, 0xcc, 0x97, 0xbe, 0xcc, 0x0d, 0xf9, 0xc2, 0xe6, 0x22, 0xaf,
	0xc4, 0xe6, 0x22, 0x27, 0x34, 0x60, 0xd1, 0x50, 0xe6, 0x83, 0x86, 0x2c, 0x3a, 0x97, 0xb9, 0xa0,
	0xf3, 0xe6, 0x43, 0x28, 0xa6, 0x2f, 0x1b, 0x5e, 0x86, 0x52, 0xcf, 0xf1, 0xec, 0xae, 0xeb, 0xf5,
	0xfa, 0xce, 0x23, 0xf5, 0x16, 0xae, 0x02, 0xf4, 0x1c, 0xcf, 0xe9, 0x1b, 0x86, 0xe9, 0x38, 0x2a,
	0x92, 0xf1, 0x5e, 0xdb, 0x3a, 0xe8, 0x13, 0x53, 0x55, 0x9a, 0x7f, 0x23, 0x28, 0x67, 0xbb, 0x88,
	0x57, 0x61, 0xd9, 0x70, 0xbc, 0xbe, 0x4d, 0x4c, 0xa3, 0xbb, 0x6f, 0x5b, 0xcf, 0xcc, 0x8e, 0x7a,
	0x0b, 0x57, 0xa0, 0x68, 0x30, 0x59, 0xf2, 0x4d, 0xfb, 0x40, 0x45, 0x6c, 0x15, 0x1e, 0xba, 0x7b,
	0xdd, 0xbe, 0xdd, 0x51, 0x15, 0x09, 0x38, 0x96, 0x6b, 0x7a, 0x26, 0x21, 0x2a, 0x60, 0x0c, 0x55,
	0xc3, 0xf1, 0x7a, 0xa4, 0xcb, 0x96, 0xe5, 0x58, 0x09, 0xab, 0x50, 0x36, 0x1c, 0x6f, 0xcf, 0x74,
	0x8d, 0x47, 0x1c, 0x29, 0xe3, 0x0f, 0x60, 0x3d, 0x33, 0xcd, 0xeb, 0x3b, 0xa6, 0x67, 0xb4, 0x8d,
	0x47, 0xa6, 0xba, 0x86, 0x6f, 0x83, 0x36, 0x2f, 0x90, 0xf9, 0xba, 0x8e, 0xb7, 0x60, 0x23, 0x2b,
	0x95, 0xf9, 0xb6, 0xd1, 0xfc, 0x09, 0x41, 0x39, 0x7b, 0x03, 0xe0, 0x15, 0xa8, 0xf4, 0x1e, 0xef,
	0x67, 0xf2, 0xbd, 0xc5, 0xd2, 0xe3, 0x90, 0x65, 0xbb, 0xa4, 0x6d, 0x3b, 0x96, 0xab, 0x02, 0x4b,
	0x8f, 0x63, 0x6e, 0xb7, 0x7b, 0xd0, 0xb5, 0xf7, 0xd5, 0xb5, 0x14, 0x69, 0x13, 0x62, 0x3d, 0x31,
	0x3b, 0xea, 0x87, 0xac, 0x0e, 0x1c, 0x61, 0xf5, 0x53, 0xb7, 0x53, 0x42, 0x52, 0xde, 0x46, 0xba,
	0x56, 0xfb, 0x6b, 0x59, 0x2c, 0xbd, 0xf9, 0xa9, 0xec, 0xb9, 0x48, 0xa6, 0x04, 0x8b, 0xae, 0xe3,
	0x39, 0x6e, 0xb7, 0x27, 0x9a, 0xe3, 0x3a, 0x1e, 0xe9, 0xdb, 0xb6, 0x65, 0xef, 0xab, 0xa8, 0x79,
	0x02, 0xcb, 0x97, 0xde, 0x18, 0x56, 0x59, 0xc7, 0x25, 0x5e, 0xdf, 0x7e, 0x6c, 0x77, 0x9f, 0xda,
	0x62, 0x0e, 0x03, 0xcc, 0xef, 0x7a, 0x16, 0x31, 0x55, 0xc4, 0x04, 0x59, 0xdc, 0xee, 0x59, 0xaa,
	0xc2, 0xf6, 0xc5, 0x03, 0xe2, 0x5a, 0x7b, 0x96, 0x61, 0xb5, 0x0f, 0xd4, 0x1c, 0xde, 0x84, 0x55,
	0x86, 0x59, 0xf6, 0x93, 0xf6, 0x81, 0xd5, 0xf1, 0x0c, 0xb6, 0x1b, 0x93, 0xa8, 0xf9, 0xc3, 0x05,
	0xfe, 0x0f, 0xeb, 0xe7, 0xff, 0x05, 0x00, 0x00, 0xff, 0xff, 0xf8, 0x19, 0x42, 0x47, 0xc1, 0x0e,
	0x00, 0x00,
}
